CUSTOMERS_MAP = {
    'sex': 'sex',
    'website_id': 'ids.websiteID',
    'mindbox_id': 'ids.mindboxId',
    'birth_date': 'birthDate',
    'first_name': 'firstName',
    'middle_name': 'middleName',
    'last_name': 'lastName',
    'iana_time_zone': 'ianaTimeZone',
    'time_zone_source': 'timeZoneSource',
    'is_email_invalid': 'isEmailInvalid',
    'is_mobile_phone_invalid': 'isMobilePhoneInvalid',
    'change_date_time_utc': 'changeDateTimeUtc',
    'is_mobile_phone_confirmed': 'isMobilePhoneConfirmed',
    'email': 'email',
    'mobile_phone': 'mobilePhone',
}

ACTIONS_MAP = {
    'mindbox_id': 'ids.mindboxId',
    'date_time_utc': 'dateTimeUtc',
    'action_template_name': 'actionTemplate.name',
    'channel_name': 'channel.name',
    'customer_id': 'customer.ids.mindboxId',
}

ORDERS_MAP = {
    'customer_id': 'customer.ids.mindboxId',
    'mindbox_id': 'ids.mindboxId',
    'offline_id': 'ids.offlineID',
    'order_transaction_id': 'ids.orderTransactionIdAutogenerated',
    'first_action_mindbox_id': 'firstAction.ids.mindboxId',
    'first_action_datetime_utc': 'firstAction.dateTimeUtc',
    'channel_mindbox_id': 'firstAction.channel.ids.mindboxId',
    'channel_external_id': 'firstAction.channel.ids.externalId',
    'channel_name': 'firstAction.channel.name',
    'transaction_external_id': 'transaction.ids.externalId',
    'total_price': 'totalPrice',
}

LINES_MAP = {
    'order_id': 'order_id',
    'product_riteil1c_id': 'product.ids.riteil1C',
    'product_name': 'product.name',
    'quantity': 'quantity',
    'base_price_per_item': 'basePricePerItem',
    'price_of_line': 'priceOfLine',
    'status_external_id': 'status.ids.externalId',
}

BONUS_POINTS_MAP = {
    'order_id': 'order_id',
    'balance_type_system_name': 'balanceType.ids.systemName',
    'balance_type_name': 'balanceType.name',
    'earned_amount': 'earnedAmount',
    'spent_amount': 'spentAmount',
}

PROMOTIONS_MAP = {
    'order_id': 'order_id',
    'promotion_type': 'type',
    'promotion_mindbox_id': 'promotion.ids.mindboxId',
    'promotion_external_id': 'promotion.ids.externalId',
    'promotion_name': 'promotion.name',
    'promotion_type_name': 'promotion.type',
    'grouping_key': 'groupingKey',
    'amount': 'amount',
    'balance_type_system_name': 'balanceType.ids.systemName',
    'balance_type_name': 'balanceType.name',
    'expiration_datetime_utc': 'expirationDateTimeUtc',
}

YANDEX_DIMENSIONS_ONE_MAP = {
    'ym:s:purchaseID': 'purchase_id',
    'ym:s:visitID': 'visit_id',

    'ym:s:clientID': 'client_id',
    'ym:s:dateTime': 'date_time',
    'ym:s:purchaseRevenue': 'purchase_revenue',
}

YANDEX_DIMENSIONS_TWO_MAP = {
    'ym:s:purchaseID': 'purchase_id',
    'ym:s:visitID': 'visit_id',

    'ym:s:dateTime': 'date_time',
    'ym:s:TrafficSource': 'traffic_source',
    'ym:s:lastSearchEngine': 'last_search_engine',
    'ym:s:UTMSource': 'utm_source',
    'ym:s:UTMMedium': 'utm_medium',
    'ym:s:UTMCampaign': 'utm_campaign',
    'ym:s:UTMContent': 'utm_content',
    'ym:s:UTMTerm': 'utm_term',
}

YANDEX_DIMENSIONS_THREE_MAP = {
    'ym:s:purchaseID': 'purchase_id',
    'ym:s:visitID': 'visit_id',

    'ym:s:dateTime': 'date_time',
    'ym:s:deviceCategory': 'device_category',
    'ym:s:ReferalSource': 'referal_source',
}

YANDEX_DIMENSIONS_FOUR_MAP = {
    'ym:s:visitID': 'yandex_visit_id',

    'ym:s:dateTime': 'date_time',
    'ym:s:goal': 'goal',
}

YANDEX_GOALS_TO_VISITS_FIELDS_MAP = {
    'parent_db': 'df_yandex_visits',
    'from': 'yandex_visit_id',
    'to': 'visit_id',
}
